export const emojisOnWheel = [
  { emoji: "😸", color: "bg-pink-200" },
  { emoji: "👾", color: "bg-purple-200" },
  { emoji: "😈", color: "bg-blue-200" },
  { emoji: "🐶", color: "bg-green-200" },
  { emoji: "🐸", color: "bg-yellow-200" },
  { emoji: "🐰", color: "bg-orange-200" },
  { emoji: "🐛", color: "bg-rose-200" },
  { emoji: "🦄", color: "bg-indigo-200" },
  { emoji: "🐕", color: "bg-teal-200" },
  { emoji: "🍁", color: "bg-amber-200" },
  { emoji: "🌹", color: "bg-cyan-200" },
  { emoji: "🥑", color: "bg-lime-200" },
  { emoji: "🎂", color: "bg-fuchsia-200" },
  { emoji: "🎷", color: "bg-emerald-200" },
  { emoji: "🏡", color: "bg-violet-200" },
  { emoji: "🏔️", color: "bg-violet-200" },
  { emoji: "🕹️", color: "bg-violet-200" },
  { emoji: "💙", color: "bg-violet-200" },
] as const;